apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sealed-secrets
  namespace: argocd
spec:
  project: default
  source:
    repoURL: oci://REGISTRY_NAME/REPOSITORY_NAME/postgresql
    targetRevision: 16.2.0
    helm:
      releaseName: postgresql
  destination:
    server: "https://kubernetes.default.svc"
    namespace: postgresql

   syncPolicy:
    syncOptions:
    - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true